version: "3.9"
services:
  web:
    container_name: sheddit_web
    build: .
    command: sh -c "./wait-for.sh mysql:3306 reids:6379 -- ./sheddit ./config/config.yaml"
    depends_on:
      - mysql
      - redis
    ports:
      - "8088:8088"
    restart: always
  mysql:
    container_name: sheddit_mysql
    image: mysql:8.0.32
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sheddit"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    container_name: sheddit_redis
    image: redis:7.0.8
    ports:
      - "16379:6379"
    command: redis-server --requirepass redis
    restart: always