apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/sheddit-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./wait-for.sh mysql:3306 reids:6379 -- ./sheddit ./config/config.yaml
          image: web
          name: sheddit-web
          ports:
            - containerPort: 8088
              hostPort: 8088
              protocol: TCP
      restartPolicy: Always
